DROP TABLE typo;

CREATE TABLE typo (
  id SERIAL UNIQUE PRIMARY KEY NOT NULL,
  wpm INTEGER NOT NULL,
  date_time
)

CREATE TABLE average (
  id SERIAL UNIQUE PRIMARY KEY NOT NULL,
  total_wpm INTEGER NOT NULL DEFAULT 0,
  average_wpm INTEGER NOT NULL,
)